package io.github.ulisse1996.integration.test.query;

import io.github.ulisse1996.BaseDao;
import io.github.ulisse1996.annotation.Dao;
import io.github.ulisse1996.integration.test.entity.AutoGenerated;

@Dao
public interface AutoGenDao extends BaseDao<AutoGenerated> {}
