package io.github.ulisse1996.integration.test.entity;

import io.github.ulisse1996.annotation.Column;
import io.github.ulisse1996.annotation.Id;
import io.github.ulisse1996.annotation.Table;

import java.math.BigDecimal;

@Table(name = "AUTO_GEN")
public class AutoGenerated {

    @Id(autoGenerated = true)
    @Column(name = "GEN_ID")
    private BigDecimal colGen;

    @Column(name = "NAME")
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getColGen() {
        return colGen;
    }

    public void setColGen(BigDecimal colGen) {
        this.colGen = colGen;
    }
}
