package io.github.ulisse1996.jaorm.processor.generation.impl;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.Compiler;
import io.github.ulisse1996.jaorm.processor.JaormProcessor;
import org.junit.jupiter.api.Test;

class AutoGeneratedGeneratorTest extends CompilerTest {

    @Test
    void should_create_generators_with_table_generated() {
        Compilation compilation = Compiler.javac()
                .withProcessors(new JaormProcessor())
                .compile(
                        getFile("generated", "EntityWithTableGenerated.java"),
                        getFile("generated", "EntityWithTableGeneratedWithoutId.java")
                );
        checkCompilation(compilation);
    }

    @Test
    void should_create_generators_with_custom_generated() {
        Compilation compilation = Compiler.javac()
                .withProcessors(new JaormProcessor())
                .compile(
                        getFile("generated", "EntityWithCustomGenerated.java"),
                        getFile("generated", "EntityWithCustomGeneratedWithoutId.java")
                );
        checkCompilation(compilation);
    }
}
