package io.github.ulisse1996.jaorm.entity;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.function.Supplier;

public interface EntityDelegate<T> {

    Supplier<T> getEntityInstance();
    EntityMapper<T> getEntityMapper();
    void setEntity(ResultSet rs) throws SQLException;
    void setFullEntity(T entity);
    T getEntity();
    String getBaseSql();
    String getKeysWhere();
    String getInsertSql();
    String[] getSelectables();
    String getTable();
    String getUpdateSql();
    String getDeleteSql();
    boolean isModified();
    void setUpdateRow(int row);
    int getAndResetUpdateRow();
    default void setAutoGenerated(Map<String, Object> generated) {
        if (!generated.isEmpty()) {
            EntityMapper<T> mapper = getEntityMapper();
            T entity = getEntity();
            for (Map.Entry<String, Object> entry : generated.entrySet()) {
                mapper.setGenerated(entity, entry.getKey(), entry.getValue());
            }
        }
    }
    default Map<String, Class<?>> getAutoGeneratedKeys() {
        return getEntityMapper().getAutoGeneratedKeys();
    }
    default T toEntity(ResultSet rs) throws SQLException {
        return getEntityMapper().map(getEntityInstance(), rs);
    }
}
