package io.jaorm.integration.test.query;

import io.jaorm.BaseDao;
import io.jaorm.annotation.Dao;
import io.jaorm.integration.test.entity.AutoGenerated;

@Dao
public interface AutoGenDao extends BaseDao<AutoGenerated> {}
