package io.github.ulisse1996.jaorm.integration.test.entity;

import io.github.ulisse1996.jaorm.annotation.Column;
import io.github.ulisse1996.jaorm.annotation.Id;
import io.github.ulisse1996.jaorm.annotation.Table;
import lombok.Data;

import java.math.BigInteger;

@Table(name = "PAYMENTS")
@Data
public class Payment {

    @Id(autoGenerated = true)
    @Column(name = "PAYMENT_ID")
    private BigInteger id;

    @Column(name = "TYPE")
    private String type;
}
