package io.github.ulisse1996.jaorm.integration.test.entity;

import io.github.ulisse1996.jaorm.annotation.*;
import lombok.Data;

import java.math.BigInteger;

@Table(name = "TRANSACTIONS")
@Data
public class Transaction {

    @Id(autoGenerated = true)
    @Column(name = "TRANSACTION_ID")
    private BigInteger id;

    @Column(name = "RESERVATION_ID")
    private BigInteger reservationId;

    @Column(name = "PAYMENT_ID")
    private BigInteger paymentId;

    @Cascade(CascadeType.ALL)
    @Relationship(columns = @Relationship.RelationshipColumn(sourceColumn = "RESERVATION_ID", targetColumn = "RESERVATION_ID"))
    private Reservation reservation;

    @Cascade(CascadeType.ALL)
    @Relationship(columns = @Relationship.RelationshipColumn(sourceColumn = "PAYMENT_ID", targetColumn = "PAYMENT_ID"))
    private Payment payment;
}
