package io.github.ulisse1996.jaorm.integration.test.entity;

import io.github.ulisse1996.jaorm.annotation.Column;
import io.github.ulisse1996.jaorm.annotation.Id;
import io.github.ulisse1996.jaorm.annotation.Table;

import java.math.BigDecimal;
import java.util.Objects;

@Table(name = "MY_PROG")
public class EntityWithProgressive {

    @Id(autoGenerated = true)
    @Column(name = "ID_COL")
    private BigDecimal id;

    @Column(name = "PROGR", autoGenerated = true)
    private BigDecimal progressive;

    @Column(name = "MY_VALUE")
    private String value;

    public BigDecimal getId() {
        return id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public BigDecimal getProgressive() {
        return progressive;
    }

    public void setProgressive(BigDecimal progressive) {
        this.progressive = progressive;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        EntityWithProgressive that = (EntityWithProgressive) o;
        return Objects.equals(id, that.id) && Objects.equals(progressive, that.progressive) && Objects.equals(value, that.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, progressive, value);
    }
}
