package io.github.ulisse1996.jaorm.integration.test.entity;

import io.github.ulisse1996.jaorm.annotation.Column;
import io.github.ulisse1996.jaorm.annotation.Id;
import io.github.ulisse1996.jaorm.annotation.Table;
import io.github.ulisse1996.jaorm.annotation.TableGenerated;

import java.math.BigDecimal;

@Table(name = "SEQUENCE_T")
public class Sequence {

    @Id(autoGenerated = true)
    @Column(name = "MY_ID")
    @TableGenerated(tableName = "SEQ_TABLE", valueColumn = "SEQ_VAL", keyColumn = "ID_SEQ", matchKey = "ENTITY")
    private BigDecimal id;

    @Column(name = "MY_SEQ", autoGenerated = true)
    @TableGenerated(tableName = "SEQ_TABLE", valueColumn = "SEQ_VAL", keyColumn = "ID_SEQ", matchKey = "ENTITY")
    public BigDecimal seq;

    @Column(name = "MY_VAL")
    private String val;

    public BigDecimal getId() {
        return id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public BigDecimal getSeq() {
        return seq;
    }

    public void setSeq(BigDecimal seq) {
        this.seq = seq;
    }

    public String getVal() {
        return val;
    }

    public void setVal(String val) {
        this.val = val;
    }
}
